-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Video Games"
(
    "Index" bigint NOT NULL,
    "Title" character varying COLLATE pg_catalog."default" NOT NULL,
    "Release_Date" character varying(10)[] COLLATE pg_catalog."default",
    "Developers" character varying COLLATE pg_catalog."default",
    "Platforms" character varying COLLATE pg_catalog."default",
    "Genres" character varying COLLATE pg_catalog."default",
    "Rating" character varying COLLATE pg_catalog."default",
    "Plays" character varying COLLATE pg_catalog."default",
    "Playing" INT COLLATE pg_catalog."default",
    "Backlogs" INT COLLATE pg_catalog."default",
    "Wishlist" INT COLLATE pg_catalog."default",
    "Lists" INT COLLATE pg_catalog."default",
    "Reviews" INT COLLATE pg_catalog."default",
    CONSTRAINT "Index" PRIMARY KEY ("Index")
);
END;